# Czech UI copy for coping methods (human translation). Keys mirror Excel export.
# ruff: noqa: E501

CS_BY_ID = {
    "B01": {
        "ID": "B01",
        "Name (Professional)": "Krabicové dýchání (4-4-4-4)",
        "Name (Child-friendly)": "Dýchání do čtverce",
        "Modality": "Tělo",
        "Source(s)": "DBT Skills Manual (Linehan, 2015); Ma et al. (2017) Front Psychol; pokyny Cedars-Sinai pro děti a dospívající",
        "Age Range": "8–18",
        "Target Emotional State(s)": "Akutní panika; Difúzní úzkost; Hněv/vztek; Potíže se spánkem; Stres ve škole",
        "Activation Energy": "Nízká",
        "Time to Effect": "Okamžitý (30–60 s)",
        "Duration of Activity": "2–10 min",
        "Required Objects": "Nic",
        "Setting Constraints": "Kdekoli (včetně školy/veřejnosti)",
        "Brief Mechanism": "Pomalý výdech aktivuje nervus vagus → posun k parasympatiku; delší výdech snižuje tep a hladinu kortizolu.",
        "Bridges to Help-Seeking": "Ne",
        "Repeatability": "Lze opakovat neomezeně",
        "Evidence Strength": "Silná",
        "Czech Adaptation Notes": "Aplikace Nepanikař obsahuje moduly s vedeným dýcháním; Nevypušť duši doporučuje dechová cvičení.",
    },
    "B02": {
        "ID": "B02",
        "Name (Professional)": "Diafragmatické (břišní) dýchání",
        "Name (Child-friendly)": "Hluboký dech",
        "Modality": "Tělo",
        "Source(s)": "Přehled PMC (2025) o diafragmatickém dýchání u populace 6–18 let; Kelty Mental Health; NCCIH",
        "Age Range": "8–18",
        "Target Emotional State(s)": "Akutní panika; Difúzní úzkost; Hněv/vztek; Ruminace",
        "Activation Energy": "Nízká",
        "Time to Effect": "Okamžitý (30–60 s)",
        "Duration of Activity": "2–15 min",
        "Required Objects": "Nic (volitelně: ruka na břiše)",
        "Setting Constraints": "Kdekoli",
        "Brief Mechanism": "Rozpínání bránice stimuluje vagální aferenty → snižuje sympatickou aktivaci; posiluje interocepci.",
        "Bridges to Help-Seeking": "Ne",
        "Repeatability": "Lze opakovat neomezeně",
        "Evidence Strength": "Silná",
        "Czech Adaptation Notes": "92 % dětských účastníků programů s diafragmatickým dýcháním hlásilo výrazné uvolnění.",
    },
    "B03": {
        "ID": "B03",
        "Name (Professional)": "Progresivní svalová relaxace",
        "Name (Child-friendly)": "Pevný stisk",
        "Modality": "Tělo",
        "Source(s)": "Jacobson (1938); Toussaint et al. (2021) ECAM; studie JPMR 8–17 let (2025 MDPI Medicina)",
        "Age Range": "8–18 (8–12 přizpůsobit hravými nápovědami)",
        "Target Emotional State(s)": "Difúzní úzkost; Hněv/vztek; Potíže se spánkem; Stres ve škole",
        "Activation Energy": "Střední",
        "Time to Effect": "Krátký (3–5 min)",
        "Duration of Activity": "10–20 min",
        "Required Objects": "Nic (volitelně: podložka/postel)",
        "Setting Constraints": "Soukromý klidný prostor",
        "Brief Mechanism": "Cyklus napětí–uvolnění vytváří proprioceptivní kontrast → svaly klesnou pod výchozí úroveň; snižuje kortizol; Cohenovo d = 1,12 v pediatrické RCT.",
        "Bridges to Help-Seeking": "Ne",
        "Repeatability": "Opakovatelné (celý cyklus nebo zkráceně)",
        "Evidence Strength": "Silná",
        "Czech Adaptation Notes": "Jacobsonova progresivní relaxace je zmíněna v materiálech Nevypusť duši.",
    },
    "B04": {
        "ID": "B04",
        "Name (Professional)": "Krátký intenzivní fyzický výdej",
        "Name (Child-friendly)": "Rychlé vybití",
        "Modality": "Tělo",
        "Source(s)": "Harvard Health (2020) Cvičením ke zklidnění; DBT dovednost TIPP (intenzivní pohyb); techniky Linky bezpečí #zvladni20",
        "Age Range": "8–18",
        "Target Emotional State(s)": "Hněv/vztek; Akutní panika; Nutkání se ublížit; Smutek/ochromení",
        "Activation Energy": "Střední",
        "Time to Effect": "Okamžitý až krátký (1–5 min)",
        "Duration of Activity": "5–15 min",
        "Required Objects": "Nic (prostor na pohyb)",
        "Setting Constraints": "Je potřeba trochu místa (pokoj, chodba, venku)",
        "Brief Mechanism": "Intenzivní pohyb zpracovává stresové hormony (adrenalin, kortizol); uvolňuje endorfiny; přesměruje pozornost z emocí na tělesné vjemy.",
        "Bridges to Help-Seeking": "Ne",
        "Repeatability": "Opakovatelné",
        "Evidence Strength": "Silná",
        "Czech Adaptation Notes": "Linka bezpečí: „Pouštím si hrozně nahlas hudbu a zběsile tancuju“ — odkaz v jejich rozptylovacích technikách.",
    },
    "B05": {
        "ID": "B05",
        "Name (Professional)": "Bilaterální stimulace (Motýlí objetí)",
        "Name (Child-friendly)": "Motýlí objetí",
        "Modality": "Tělo",
        "Source(s)": "Artigas (1997); Jarero & Artigas (2024) EMDR; 12 recenzovaných studií o účinnosti; protokoly EMDR-IGTP",
        "Age Range": "8–18 (velmi dostupné pro mladší děti)",
        "Target Emotional State(s)": "Akutní panika; Disociace/pocit ne reality; Smutek/ochromení; Nutkání se ublížit",
        "Activation Energy": "Nízká",
        "Time to Effect": "Okamžitý až krátký (1–3 min)",
        "Duration of Activity": "2–10 min",
        "Required Objects": "Nic",
        "Setting Constraints": "Kdekoli (dostatečně nenápadné ve škole)",
        "Brief Mechanism": "Bilaterální stimulace zapojuje obě hemisféry; zatěžuje pracovní paměť → snižuje živost/náboj obtížného materiálu; aktivuje parasympatikus.",
        "Bridges to Help-Seeking": "Ne",
        "Repeatability": "Lze opakovat neomezeně",
        "Evidence Strength": "Silná",
        "Czech Adaptation Notes": "Vyvinuto pro přeživší trauma; široce používáno v humanitárních kontextech s dětmi; lze přizpůsobit českému prostředí.",
    },
    "B06": {
        "ID": "B06",
        "Name (Professional)": "Somatické uvolnění napětí (Tremoring)",
        "Name (Child-friendly)": "Vyklepání",
        "Modality": "Tělo",
        "Source(s)": "Somatic Experiencing (Levine, 1997); trauma-informované tělesné postupy; Kelty Mental Health",
        "Age Range": "8–18",
        "Target Emotional State(s)": "Hněv/vztek; Disociace/pocit ne reality; Akutní panika",
        "Activation Energy": "Nízká",
        "Time to Effect": "Okamžitý (15–60 s)",
        "Duration of Activity": "1–3 min",
        "Required Objects": "Nic",
        "Setting Constraints": "Spíše soukromí nebo akceptující prostředí",
        "Brief Mechanism": "Tělesné vybití uložené stresové energie dobrovolným třesením podobným nechtěnému; reset autonomního nervstva.",
        "Bridges to Help-Seeking": "Ne",
        "Repeatability": "Lze opakovat neomezeně",
        "Evidence Strength": "Střední",
        "Czech Adaptation Notes": None,
    },
    "B07": {
        "ID": "B07",
        "Name (Professional)": "Izometrická svalová kontrakce",
        "Name (Child-friendly)": "Odtlačení zdi",
        "Modality": "Tělo",
        "Source(s)": "DBT úprava tolerance tísně; literatura o proprioceptivní stimulaci v ergoterapii",
        "Age Range": "8–18",
        "Target Emotional State(s)": "Hněv/vztek; Akutní panika; Nutkání se ublížit; Stres ve škole",
        "Activation Energy": "Nízká",
        "Time to Effect": "Okamžitý (15–30 s)",
        "Duration of Activity": "1–3 min",
        "Required Objects": "Zeď nebo zárubně",
        "Setting Constraints": "Kdekoli (velmi nenápadné — školní chodba, WC)",
        "Brief Mechanism": "Izometrické napětí svalů dává silný proprioceptivní vstup → zklidnění; přesměruje impulz „bojovat“ do kontrolované námahy bez újmy.",
        "Bridges to Help-Seeking": "Ne",
        "Repeatability": "Lze opakovat neomezeně",
        "Evidence Strength": "Střední",
        "Czech Adaptation Notes": None,
    },
    "B08": {
        "ID": "B08",
        "Name (Professional)": "Sekvence jógových ásan",
        "Name (Child-friendly)": "Tři pozice",
        "Modality": "Tělo",
        "Source(s)": "Hagen & Nayar (2014) jóga a dětská úzkost; více RCT v přehledu IntechOpen (2025)",
        "Age Range": "8–18 (8–12 jednodušší pozice)",
        "Target Emotional State(s)": "Difúzní úzkost; Smutek/ochromení; Potíže se spánkem; Stres ve škole",
        "Activation Energy": "Střední",
        "Time to Effect": "Krátký (3–5 min)",
        "Duration of Activity": "5–20 min",
        "Required Objects": "Podložka nebo měkký povrch (volitelně)",
        "Setting Constraints": "Prostor na zemi; částečné soukromí",
        "Brief Mechanism": "Kombinuje propriocepci, regulaci dechu a interoceptivní pozornost; aktivuje parasympatikus; zlepšuje tělesné uvědomění.",
        "Bridges to Help-Seeking": "Ne",
        "Repeatability": "Opakovatelné",
        "Evidence Strength": "Silná",
        "Czech Adaptation Notes": None,
    },
    "B09": {
        "ID": "B09",
        "Name (Professional)": "Všímavá regulovaná chůze",
        "Name (Child-friendly)": "Pomalý krok",
        "Modality": "Tělo",
        "Source(s)": "Behaviorální aktivace v KBT; mindfulness-based stress reduction (MBSR); pokyny GoodRx Health pro děti",
        "Age Range": "8–18",
        "Target Emotional State(s)": "Ruminace/spirály myšlenek; Smutek/ochromení; Difúzní úzkost; Osamělost",
        "Activation Energy": "Střední",
        "Time to Effect": "Krátký až střední (5–10 min)",
        "Duration of Activity": "10–30 min",
        "Required Objects": "Obuv (volitelně)",
        "Setting Constraints": "Venku nebo uvnitř (chodba); spíše klidněji",
        "Brief Mechanism": "Rytmický oboustranný pohyb; pozornost k tělu a okolí; jemná kardio aktivace snižuje kortizol.",
        "Bridges to Help-Seeking": "Ano (docházka na místo, kde jsou lidé)",
        "Repeatability": "Opakovatelné",
        "Evidence Strength": "Silná",
        "Czech Adaptation Notes": None,
    },
    "B10": {
        "ID": "B10",
        "Name (Professional)": "Somatický kontejnment (Sebeobjetí)",
        "Name (Child-friendly)": "Pevné objetí",
        "Modality": "Tělo",
        "Source(s)": "Polyvagální teorie (Porges); somatické trauma postupy; klinické doporučení",
        "Age Range": "8–18 (zejména 8–12)",
        "Target Emotional State(s)": "Akutní panika; Disociace/pocit ne reality; Osamělost; Smutek/ochromení",
        "Activation Energy": "Nízká",
        "Time to Effect": "Okamžitý (10–30 s)",
        "Duration of Activity": "1–5 min",
        "Required Objects": "Nic",
        "Setting Constraints": "Kdekoli",
        "Brief Mechanism": "Pevný tlak na trup aktivuje receptory hlubokého tlaku → podporuje oxytocin; dává nervové soustavě signál „obklopení a bezpečí“.",
        "Bridges to Help-Seeking": "Ne",
        "Repeatability": "Lze opakovat neomezeně",
        "Evidence Strength": "Střední",
        "Czech Adaptation Notes": None,
    },
    "B11": {
        "ID": "B11",
        "Name (Professional)": "Vokální stimulace bloudivého nervu",
        "Name (Child-friendly)": "Bzučení",
        "Modality": "Tělo",
        "Source(s)": "Výzkum vagálního tonusu (Porges); bzučivý dech (Bhramari) v józe; klinický konsensus",
        "Age Range": "8–18",
        "Target Emotional State(s)": "Akutní panika; Difúzní úzkost; Disociace/pocit ne reality",
        "Activation Energy": "Nízká",
        "Time to Effect": "Okamžitý (15–60 s)",
        "Duration of Activity": "1–5 min",
        "Required Objects": "Nic",
        "Setting Constraints": "Polosoukromí (nebo sluchátka jako maskování)",
        "Brief Mechanism": "Bzučení rozechvívá hrtanové svaly u nervu vagus → přímá vagální stimulace; efekt prodlouženého výdechu; zvuková sebeútěcha.",
        "Bridges to Help-Seeking": "Ne",
        "Repeatability": "Lze opakovat neomezeně",
        "Evidence Strength": "Střední",
        "Czech Adaptation Notes": None,
    },
    "B12": {
        "ID": "B12",
        "Name (Professional)": "Proprioceptivní uzemnění (přes chodidla)",
        "Name (Child-friendly)": "Dupání",
        "Modality": "Tělo",
        "Source(s)": "Somatic Experiencing; trauma-informované uzemnění; ergoterapie",
        "Age Range": "8–18",
        "Target Emotional State(s)": "Disociace/pocit ne reality; Hněv/vztek; Akutní panika",
        "Activation Energy": "Nízká",
        "Time to Effect": "Okamžitý (10–30 s)",
        "Duration of Activity": "1–3 min",
        "Required Objects": "Podlaha/povrch",
        "Setting Constraints": "Kdekoli (lze nenápadně — pevně přitlačit chodidla)",
        "Brief Mechanism": "Silný proprioceptivní vstup přes chodidla znovu propojuje s tělem; bilaterální stimulace; vede energii hněvu dolů.",
        "Bridges to Help-Seeking": "Ne",
        "Repeatability": "Lze opakovat neomezeně",
        "Evidence Strength": "Střední",
        "Czech Adaptation Notes": None,
    },
    "S01": {
        "ID": "S01",
        "Name (Professional)": "Senzorické ukotvení 5-4-3-2-1",
        "Name (Child-friendly)": "Pět smyslů",
        "Modality": "Smysly",
        "Source(s)": "Uzemnění v KBT/DBT; RCT u dětí s Tourettovým syndromem (úbytek úzkosti o 36 bodů); Lang et al. (2022) JBCT",
        "Age Range": "8–18",
        "Target Emotional State(s)": "Akutní panika; Disociace/pocit ne reality; Difúzní úzkost; Ruminace",
        "Activation Energy": "Nízká",
        "Time to Effect": "Okamžitý až krátký (1–3 min)",
        "Duration of Activity": "3–5 min",
        "Required Objects": "Nic",
        "Setting Constraints": "Kdekoli (včetně školy/veřejnosti)",
        "Brief Mechanism": "Strukturovaná smyslová pozornost zapojuje prefrontální kůru → přeruší smyčku úzkosti řízenou amygdalou; vrací do přítomnosti.",
        "Bridges to Help-Seeking": "Ne",
        "Repeatability": "Lze opakovat neomezeně",
        "Evidence Strength": "Silná",
        "Czech Adaptation Notes": "Časté v českých materiálech duševního zdraví; Nepanikař obsahuje moduly uzemnění.",
    },
    "S02": {
        "ID": "S02",
        "Name (Professional)": "Čichové ukotvení (Olfa-terapie)",
        "Name (Child-friendly)": "Vůně bezpečí",
        "Modality": "Smysly",
        "Source(s)": "DBT dovednost Sebeuklidnění (čich); spojení čich–limbický systém; klinické doporučení",
        "Age Range": "8–18",
        "Target Emotional State(s)": "Akutní panika; Difúzní úzkost; Smutek/ochromení; Disociace",
        "Activation Energy": "Nízká",
        "Time to Effect": "Okamžitý (5–15 s)",
        "Duration of Activity": "1–5 min",
        "Required Objects": "Předmět s vůní (mýdlo, esenciální olej, koření, krém, čaj)",
        "Setting Constraints": "Kdekoli (do kapsy/tašky)",
        "Brief Mechanism": "Čichový nerv má přímou cestu k amygdale a hipokampu → obchází plné kognitivní zpracování; může rychle vyvolat pozitivní vzpomínku.",
        "Bridges to Help-Seeking": "Ne",
        "Repeatability": "Opakovatelné (do zvyknutí na vůni)",
        "Evidence Strength": "Střední",
        "Czech Adaptation Notes": None,
    },
    "S03": {
        "ID": "S03",
        "Name (Professional)": "Taktilní smyslová stimulace",
        "Name (Child-friendly)": "Hmatová kotva",
        "Modality": "Smysly",
        "Source(s)": "DBT Sebeuklidnění (dotyk); senzorická integrační terapie; ergoterapie",
        "Age Range": "8–18 (zejména 8–12)",
        "Target Emotional State(s)": "Disociace/pocit ne reality; Difúzní úzkost; Ruminace",
        "Activation Energy": "Nízká",
        "Time to Effect": "Okamžitý (15–60 s)",
        "Duration of Activity": "2–5 min",
        "Required Objects": "Jakékoli texturované předměty nablízku (látka, kámen, klíče, kůra)",
        "Setting Constraints": "Kdekoli",
        "Brief Mechanism": "Hmatová stimulace ukotvuje pozornost v těle a přítomnosti; aktivuje somatosensorickou kůru → konkuruje okruhům ruminace.",
        "Bridges to Help-Seeking": "Ne",
        "Repeatability": "Lze opakovat neomezeně",
        "Evidence Strength": "Střední",
        "Czech Adaptation Notes": None,
    },
    "S04": {
        "ID": "S04",
        "Name (Professional)": "Gustatorické přesměrování pozornosti",
        "Name (Child-friendly)": "Silná chuť",
        "Modality": "Smysly",
        "Source(s)": "DBT tolerance tísně (chuť jako sebeuklidnění); konsensus pro přesměrování nutkání",
        "Age Range": "8–18",
        "Target Emotional State(s)": "Disociace/pocit ne reality; Nutkání se ublížit; Smutek/ochromení",
        "Activation Energy": "Nízká",
        "Time to Effect": "Okamžitý (5–15 s)",
        "Duration of Activity": "1–5 min",
        "Required Objects": "Kyselý bonbón, citron, silná máta, pálivá žvýkačka",
        "Setting Constraints": "Kdekoli (nenápadně)",
        "Brief Mechanism": "Silná chuťová stimulace dává okamžitý smyslový „řez“; aktivuje trojklanný nerv → přesune pozornost z emocí na tělo bez újmy.",
        "Bridges to Help-Seeking": "Ne",
        "Repeatability": "Opakovatelné (omezeno zásobou)",
        "Evidence Strength": "Střední",
        "Czech Adaptation Notes": "Zmíněno v alternativách k sebepoškozování u Nevypusť duši.",
    },
    "S05": {
        "ID": "S05",
        "Name (Professional)": "Aktivace potápěčského reflexu chladem",
        "Name (Child-friendly)": "Studená voda",
        "Modality": "Smysly",
        "Source(s)": "DBT TIPP (teplota — mírná, ne šok); literatura vagální odpovědi",
        "Age Range": "13–18 (8–12 zjednodušit)",
        "Target Emotional State(s)": "Akutní panika; Hněv/vztek; Nutkání se ublížit",
        "Activation Energy": "Nízká",
        "Time to Effect": "Okamžitý (10–30 s)",
        "Duration of Activity": "1–3 min",
        "Required Objects": "Přístup ke studené vodě (umyvadlo, lahev)",
        "Setting Constraints": "Potřeba vody (koupelna, kuchyň)",
        "Brief Mechanism": "Mírný chlad na zápěstích/tvářích spouští potápěčský reflex → rychlý parasympatický posun; snižuje tep. Pozn.: jen jemně, ne šok/ponoření.",
        "Bridges to Help-Seeking": "Ne",
        "Repeatability": "Opakovatelné",
        "Evidence Strength": "Silná",
        "Czech Adaptation Notes": "Úprava: bez kostek ledu na kůži / náhlého ponoru kvůli bezpečnosti.",
    },
    "S06": {
        "ID": "S06",
        "Name (Professional)": "Sluchová regulace afektu (Muzikoterapie)",
        "Name (Child-friendly)": "Můj playlist",
        "Modality": "Smysly",
        "Source(s)": "Metaanalýzy hudební terapie; Thoma et al. (2013) kortizol; GoodRx Health pro děti",
        "Age Range": "8–18",
        "Target Emotional State(s)": "Smutek/ochromení; Difúzní úzkost; Hněv/vztek; Osamělost; Potíže se spánkem",
        "Activation Energy": "Nízká",
        "Time to Effect": "Krátký (1–3 min)",
        "Duration of Activity": "5–30 min",
        "Required Objects": "Telefon/zařízení a sluchátka",
        "Setting Constraints": "Kdekoli se sluchátky",
        "Brief Mechanism": "Hudba moduluje serotonin, dopamin; tempo 60–80 BPM může synchronizovat tep; text poskytuje zapojení a validaci.",
        "Bridges to Help-Seeking": "Ne",
        "Repeatability": "Lze opakovat neomezeně",
        "Evidence Strength": "Silná",
        "Czech Adaptation Notes": "Linka bezpečí odkazuje na hlasitou hudbu + tanec jako rozptyl v #zvladni20.",
    },
    "S07": {
        "ID": "S07",
        "Name (Professional)": "Hluboká tlaková stimulace",
        "Name (Child-friendly)": "Těžká deka",
        "Modality": "Smysly",
        "Source(s)": "Literatura hlubokého tlaku (DPS); Grandin (1992); ergoterapie",
        "Age Range": "8–18 (zejména 8–12)",
        "Target Emotional State(s)": "Akutní panika; Difúzní úzkost; Potíže se spánkem; Disociace",
        "Activation Energy": "Nízká",
        "Time to Effect": "Okamžitý až krátký (1–3 min)",
        "Duration of Activity": "5–30 min",
        "Required Objects": "Těžká deka, velký polštář nebo srolovaný ručník",
        "Setting Constraints": "Domov/soukromý prostor",
        "Brief Mechanism": "Hluboký tlak aktivuje parasympatikus; podporuje serotonin a dopamin; snižuje kortizol; podobné zavinutí.",
        "Bridges to Help-Seeking": "Ne",
        "Repeatability": "Opakovatelné",
        "Evidence Strength": "Střední",
        "Czech Adaptation Notes": None,
    },
    "S08": {
        "ID": "S08",
        "Name (Professional)": "Jemnomotorická regulace (Fidget)",
        "Name (Child-friendly)": "Hračka do ruky",
        "Modality": "Smysly",
        "Source(s)": "Senzorické zpracování; výzkum ADHD úprav; konsensus ergoterapie",
        "Age Range": "8–18 (zejména 8–14)",
        "Target Emotional State(s)": "Difúzní úzkost; Ruminace; Stres ve škole",
        "Activation Energy": "Nízká",
        "Time to Effect": "Okamžitý (5–15 s)",
        "Duration of Activity": "Podle potřeby",
        "Required Objects": "Fidget spinner, antistresový míček, modelína, hladký kámen, přívěsek",
        "Setting Constraints": "Kdekoli (velmi nenápadné — ve škole)",
        "Brief Mechanism": "Opakovaný hmat reguluje na nízké úrovni; zapojuje motorickou kůru → méně neklidu; smyslové ukotvení.",
        "Bridges to Help-Seeking": "Ne",
        "Repeatability": "Lze opakovat neomezeně",
        "Evidence Strength": "Střední",
        "Czech Adaptation Notes": None,
    },
    "C01": {
        "ID": "C01",
        "Name (Professional)": "Vizuální externalizace afektu",
        "Name (Child-friendly)": "Barvy pocitů",
        "Modality": "Tvořivé",
        "Source(s)": "Metaanalýza arteterapie (PMC 2024); Malchiodi (2012); Tartakovsky (2015)",
        "Age Range": "8–18 (zejména 8–14)",
        "Target Emotional State(s)": "Smutek/ochromení; Hněv/vztek; Difúzní úzkost; Stud; Ruminace",
        "Activation Energy": "Střední",
        "Time to Effect": "Krátký až střední (5–10 min)",
        "Duration of Activity": "10–30 min",
        "Required Objects": "Papír/skicák + tužky/pastelky/fixy",
        "Setting Constraints": "Kdekoli s plochou (doma, škola)",
        "Brief Mechanism": "Externalizace vnitřního stavu přes obraz; zapojuje pravou hemisféru; symbolická distance od přemáhajících pocitů; „flow“.",
        "Bridges to Help-Seeking": "Ano (kresba může otevřít rozhovor)",
        "Repeatability": "Opakovatelné (pokaždé nový obrázek)",
        "Evidence Strength": "Silná",
        "Czech Adaptation Notes": None,
    },
    "C02": {
        "ID": "C02",
        "Name (Professional)": "Expresivní nestrukturované psaní",
        "Name (Child-friendly)": "Výplach hlavy",
        "Modality": "Tvořivé",
        "Source(s)": "Pennebaker (1997) expresivní psaní; KBT záznamy myšlenek; Fukumori et al. (2017)",
        "Age Range": "10–18 (8–10 jednodušší výzvy)",
        "Target Emotional State(s)": "Ruminace/spirály myšlenek; Smutek/ochromení; Hněv/vztek; Stud; Osamělost",
        "Activation Energy": "Střední",
        "Time to Effect": "Krátký až střední (3–10 min)",
        "Duration of Activity": "5–20 min",
        "Required Objects": "Papír + pero nebo poznámky v telefonu",
        "Setting Constraints": "Soukromí (nebo nenápadný telefon)",
        "Brief Mechanism": "Psaní externalizuje kognitivní smyčky → uvolní pracovní paměť; pojmenování emocí snižuje aktivitu amygdaly.",
        "Bridges to Help-Seeking": "Ano (text snižuje práh pro sdílení)",
        "Repeatability": "Opakovatelné (téma se může měnit)",
        "Evidence Strength": "Silná",
        "Czech Adaptation Notes": "Nepanikař obsahuje modul „Moje záznamy“.",
    },
    "C03": {
        "ID": "C03",
        "Name (Professional)": "Imaginativní expoziční psaní",
        "Name (Child-friendly)": "Tajný dopis",
        "Modality": "Tvořivé",
        "Source(s)": "Narativní terapie; gestalt (prázdná židle — úprava); klinický konsensus",
        "Age Range": "10–18",
        "Target Emotional State(s)": "Hněv/vztek; Stud; Osamělost; Smutek/ochromení; Ruminace",
        "Activation Energy": "Střední",
        "Time to Effect": "Střední (10–15 min)",
        "Duration of Activity": "10–30 min",
        "Required Objects": "Papír + pero",
        "Setting Constraints": "Soukromý prostor",
        "Brief Mechanism": "Externalizuje konflikt nebo nevyjádřenou emoci; kognitivní odpoutání od vztahové tísně; pocit kontroly bez konfrontace.",
        "Bridges to Help-Seeking": "Ano (trénuje formulaci pocitů → může vést k reálnému rozhovoru)",
        "Repeatability": "Střední (v jedné session klesající přínos)",
        "Evidence Strength": "Střední",
        "Czech Adaptation Notes": "Linka bezpečí navrhuje psaný projev jako alternativu k přímé konfrontaci.",
    },
    "C04": {
        "ID": "C04",
        "Name (Professional)": "Strukturální kresba vzorů",
        "Name (Child-friendly)": "Kreslení vzorů",
        "Modality": "Tvořivé",
        "Source(s)": "Arteterapie úzkosti (meta PMC 2024); Curry & Kasser (2005); metoda Zentangle",
        "Age Range": "8–18",
        "Target Emotional State(s)": "Difúzní úzkost; Ruminace; Stres ve škole; Smutek/ochromení",
        "Activation Energy": "Střední",
        "Time to Effect": "Krátký až střední (5–10 min)",
        "Duration of Activity": "10–30 min",
        "Required Objects": "Papír + pero (nebo vytištěná mandala)",
        "Setting Constraints": "Kdekoli s plochou",
        "Brief Mechanism": "Strukturované opakující se vzory navozují flow; kotví pozornost v motorice; snižuje ruminaci v defaultním režimu.",
        "Bridges to Help-Seeking": "Ne",
        "Repeatability": "Lze opakovat neomezeně",
        "Evidence Strength": "Střední",
        "Czech Adaptation Notes": None,
    },
    "C05": {
        "ID": "C05",
        "Name (Professional)": "Kognitivní přehodnocení pomocí hudby",
        "Name (Child-friendly)": "DJ nálady",
        "Modality": "Tvořivé",
        "Source(s)": "Hudební terapie; identita a hudba u dospívajících; doporučení kliniků",
        "Age Range": "10–18",
        "Target Emotional State(s)": "Smutek/ochromení; Hněv/vztek; Osamělost; Difúzní úzkost",
        "Activation Energy": "Střední",
        "Time to Effect": "Střední (5–15 min)",
        "Duration of Activity": "10–30 min",
        "Required Objects": "Telefon s hudební aplikací",
        "Setting Constraints": "Kdekoli se sluchátky",
        "Brief Mechanism": "Aktivní výběr zapojuje exekutivní funkce a identitu; kombinuje přehodnocení (skladby sedí/mění náladu) s uklidněním hudbou.",
        "Bridges to Help-Seeking": "Ne",
        "Repeatability": "Opakovatelné",
        "Evidence Strength": "Střední",
        "Czech Adaptation Notes": None,
    },
    "C06": {
        "ID": "C06",
        "Name (Professional)": "Konstruktivně-destruktivní tvorba",
        "Name (Child-friendly)": "Trhání papíru",
        "Modality": "Tvořivé",
        "Source(s)": "Expresivní umělecká terapie; doporučení u hněvu; rozptylovací techniky Linky bezpečí",
        "Age Range": "8–18 (zejména 8–14)",
        "Target Emotional State(s)": "Hněv/vztek; Nutkání se ublížit; Ruminace",
        "Activation Energy": "Střední",
        "Time to Effect": "Okamžitý až krátký (2–5 min)",
        "Duration of Activity": "10–20 min",
        "Required Objects": "Staré časopisy, noviny, šrot papíru; volitelně lepidlo + čistý papír",
        "Setting Constraints": "Domov/soukromí",
        "Brief Mechanism": "Fyzické trhání uvolňuje energii hněvu proprioceptivně; konstruktivní „ničení“ bez újmy; nové slepení přidává pocit síly.",
        "Bridges to Help-Seeking": "Ne",
        "Repeatability": "Opakovatelné (s materiálem)",
        "Evidence Strength": "Střední",
        "Czech Adaptation Notes": "Linka bezpečí uvádí trhání papíru; podobně Nevypusť duši.",
    },
    "C07": {
        "ID": "C07",
        "Name (Professional)": "Vokální narativní externalizace",
        "Name (Child-friendly)": "Hlasovka",
        "Modality": "Tvořivé",
        "Source(s)": "Narativní terapie; výzkum sebesoucitu (Neff, 2003); doporučení kliniků",
        "Age Range": "10–18",
        "Target Emotional State(s)": "Osamělost; Smutek/ochromení; Ruminace; Stud",
        "Activation Energy": "Střední",
        "Time to Effect": "Krátký až střední (3–10 min)",
        "Duration of Activity": "5–15 min",
        "Required Objects": "Telefon s diktafonem",
        "Setting Constraints": "Soukromý prostor",
        "Brief Mechanism": "Vlastní hlas externalizuje vnitřní dialog; vytváří perspektivu pozorovatele (defúze); opakované poslechy mohou podpořit validaci.",
        "Bridges to Help-Seeking": "Ano (trénink verbalizace → snazší zavolat na linku)",
        "Repeatability": "Střední (může působit opakovaně)",
        "Evidence Strength": "Vznikající",
        "Czech Adaptation Notes": "Most k volání na Linku bezpečí 116 111.",
    },
    "C08": {
        "ID": "C08",
        "Name (Professional)": "Rytmická textová exprese",
        "Name (Child-friendly)": "Můj text / Rap",
        "Modality": "Tvořivé",
        "Source(s)": "Hudební terapie; hip-hop terapie (Tyson, 2002); literatura o tvorbě u dospívajících",
        "Age Range": "10–18",
        "Target Emotional State(s)": "Hněv/vztek; Smutek/ochromení; Osamělost; Stud; Ruminace",
        "Activation Energy": "Vysoká",
        "Time to Effect": "Střední (10–20 min)",
        "Duration of Activity": "15–45 min",
        "Required Objects": "Papír + pero nebo poznámky v telefonu",
        "Setting Constraints": "Soukromý prostor",
        "Brief Mechanism": "Strukturuje emoce v rytmu a rýmu; zapojuje exekutivní funkce; dává zkušenost mistrovství a výraz identity.",
        "Bridges to Help-Seeking": "Ano (sdílení textu jako nepřímé prozrazení)",
        "Repeatability": "Opakovatelné",
        "Evidence Strength": "Střední",
        "Czech Adaptation Notes": None,
    },
    "C09": {
        "ID": "C09",
        "Name (Professional)": "Taktilně-kinestetické modelování",
        "Name (Child-friendly)": "Modelování",
        "Modality": "Tvořivé",
        "Source(s)": "Arteterapie (Malchiodi, 2012); senzorická integrace; expresivní umění",
        "Age Range": "8–18 (zejména 8–14)",
        "Target Emotional State(s)": "Hněv/vztek; Difúzní úzkost; Nutkání se ublížit; Ruminace",
        "Activation Energy": "Střední",
        "Time to Effect": "Krátký až střední (5–10 min)",
        "Duration of Activity": "10–30 min",
        "Required Objects": "Modelína, plastelína nebo domácí solné těsto",
        "Setting Constraints": "Doma/škola (čistá plocha)",
        "Brief Mechanism": "Spojuje hmat a tvorbu; mačkání dává ventil hněvu; 3D externalizace pocitů.",
        "Bridges to Help-Seeking": "Ne",
        "Repeatability": "Opakovatelné (s materiálem)",
        "Evidence Strength": "Střední",
        "Czech Adaptation Notes": None,
    },
    "C10": {
        "ID": "C10",
        "Name (Professional)": "Somatické mapování emocí",
        "Name (Child-friendly)": "Mapa těla",
        "Modality": "Tvořivé",
        "Source(s)": "Mapování těla v arteterapii; somatické přístupy; doporučení pro děti",
        "Age Range": "8–18",
        "Target Emotional State(s)": "Disociace/pocit ne reality; Difúzní úzkost; Smutek/ochromení; Hněv/vztek",
        "Activation Energy": "Střední",
        "Time to Effect": "Střední (10–15 min)",
        "Duration of Activity": "15–30 min",
        "Required Objects": "Papír (ideálně větší) + pastelky/fixy",
        "Setting Constraints": "Soukromí nebo podobné terapeutické prostředí",
        "Brief Mechanism": "Vykreslení emocí „v těle“ propojuje somatiku a pocity; buduje slovník interocepce; proti disociaci skrze tělesnou pozornost.",
        "Bridges to Help-Seeking": "Ano (mapa jako nástroj rozhovoru s důvěryhodným dospělým)",
        "Repeatability": "Opakovatelné (v čase ukazuje vzorce)",
        "Evidence Strength": "Střední",
        "Czech Adaptation Notes": None,
    },
    "K01": {
        "ID": "K01",
        "Name (Professional)": "Kognitivní defúze (Pojmenování myšlenek)",
        "Name (Child-friendly)": "Jen myšlenka",
        "Modality": "Kognitivní",
        "Source(s)": "ACT (Hayes et al.); kognitivní defúze; DBT všímavost „pozoruj“",
        "Age Range": "10–18 (8–10 zjednodušit)",
        "Target Emotional State(s)": "Ruminace/spirály myšlenek; Difúzní úzkost; Stud; Stres ve škole",
        "Activation Energy": "Nízká",
        "Time to Effect": "Okamžitý až krátký (30 s – 2 min)",
        "Duration of Activity": "1–5 min",
        "Required Objects": "Nic",
        "Setting Constraints": "Kdekoli",
        "Brief Mechanism": "Defúze: předpona „Všímám si, že mám myšlenku…“ vytváří odstup od obsahu → méně splývání s negativní kognicí.",
        "Bridges to Help-Seeking": "Ne",
        "Repeatability": "Lze opakovat neomezeně",
        "Evidence Strength": "Silná",
        "Czech Adaptation Notes": "ACT je v české klinické psychologii běžně používané.",
    },
    "K02": {
        "ID": "K02",
        "Name (Professional)": "Imaginace bezpečného místa",
        "Name (Child-friendly)": "Bezpečné místo",
        "Modality": "Kognitivní",
        "Source(s)": "EMDR protokol klidného/bezpečného místa; RCT vedené imaginace; přehled IntechOpen (2025) u dětí",
        "Age Range": "8–18",
        "Target Emotional State(s)": "Akutní panika; Difúzní úzkost; Potíže se spánkem; Disociace; Osamělost",
        "Activation Energy": "Nízká až střední",
        "Time to Effect": "Krátký (2–5 min)",
        "Duration of Activity": "5–15 min",
        "Required Objects": "Nic (volitelně nahrávka)",
        "Setting Constraints": "Spíše ticho; lze i se zavřenýma očima kdekoliv",
        "Brief Mechanism": "Vedená představa aktivuje podobné okruhy jako reálné smysly; konkurenční pozitivní stav; snižuje aktivitu amygdaly přes příjemnou paměť/představu.",
        "Bridges to Help-Seeking": "Ne",
        "Repeatability": "Lze opakovat neomezeně",
        "Evidence Strength": "Silná",
        "Czech Adaptation Notes": "EMDR-IGTP se používá i u nás; vedená představa v práci s dětmi běžná.",
    },
    "K03": {
        "ID": "K03",
        "Name (Professional)": "Kontrola stimulu (Odložení starostí)",
        "Name (Child-friendly)": "Okénko starostí",
        "Modality": "Kognitivní",
        "Source(s)": "KBT stimulus control pro starosti (Borkovec, 1983); doporučení u GAD",
        "Age Range": "10–18",
        "Target Emotional State(s)": "Ruminace/spirály myšlenek; Difúzní úzkost; Stres ve škole",
        "Activation Energy": "Střední",
        "Time to Effect": "Krátký (1–3 min na zavedení)",
        "Duration of Activity": "Strategie: 15 min „času na starosti“ později",
        "Required Objects": "Nic (volitelně papír na poznámku)",
        "Setting Constraints": "Kdekoli",
        "Brief Mechanism": "Naplánované okénko přeruší okamžitou posilovací smyčku ruminace; trénuje flexibilitu; většina starostí později působí méně naléhavě.",
        "Bridges to Help-Seeking": "Ne",
        "Repeatability": "Denně opakovatelné",
        "Evidence Strength": "Silná",
        "Czech Adaptation Notes": None,
    },
    "K04": {
        "ID": "K04",
        "Name (Professional)": "Kognitivní restrukturalizace (Sebesoucit)",
        "Name (Child-friendly)": "Nejlepší kamarád",
        "Modality": "Kognitivní",
        "Source(s)": "KBT restrukturalizace; sebesoucit (Neff, 2003); doporučení Nevypusť duši",
        "Age Range": "10–18",
        "Target Emotional State(s)": "Stud; Ruminace; Stres ve škole; Smutek/ochromení",
        "Activation Energy": "Střední",
        "Time to Effect": "Krátký (2–5 min)",
        "Duration of Activity": "3–10 min",
        "Required Objects": "Nic",
        "Setting Constraints": "Kdekoli",
        "Brief Mechanism": "Perspektiva „co bys řekl kamarádovi?“ přeruší sebekritickou smyčku; soucit k sobě aktivuje affiliativní systém → méně dominance hrozby.",
        "Bridges to Help-Seeking": "Ano (trénuje jazyk soucitu použitelný s druhými)",
        "Repeatability": "Opakovatelné",
        "Evidence Strength": "Silná",
        "Czech Adaptation Notes": "Nevypusť duši: „mluvit k sobě soucitně, jako k nejlepšímu příteli“.",
    },
    "K05": {
        "ID": "K05",
        "Name (Professional)": "Inhibice impulzů (Dovednost STOP)",
        "Name (Child-friendly)": "STOP!",
        "Modality": "Kognitivní",
        "Source(s)": "DBT přežití krize (Linehan, 2015); běžné v adolescentní DBT",
        "Age Range": "10–18 (8–10 zjednodušit)",
        "Target Emotional State(s)": "Akutní panika; Hněv/vztek; Nutkání se ublížit",
        "Activation Energy": "Nízká",
        "Time to Effect": "Okamžitý (15–30 s)",
        "Duration of Activity": "30 s – 2 min",
        "Required Objects": "Nic",
        "Setting Constraints": "Kdekoli",
        "Brief Mechanism": "S-T-O-P: Stop, Udělej krok zpět, Pozoruj, Pokračuj všímavě. Vytvoří pauzu mezi spouštěčem a reakcí → PF kůra dřív než impulz.",
        "Bridges to Help-Seeking": "Ne",
        "Repeatability": "Lze opakovat neomezeně",
        "Evidence Strength": "Silná",
        "Czech Adaptation Notes": None,
    },
    "K06": {
        "ID": "K06",
        "Name (Professional)": "Všímavé pozorování nutkání (Urge Surfing)",
        "Name (Child-friendly)": "Jízda na vlně",
        "Modality": "Kognitivní",
        "Source(s)": "Marlatt; DBT tolerance tísně (Linehan); materiály Therapist Aid; DBT-A",
        "Age Range": "13–18 (potřeba abstraktního myšlení)",
        "Target Emotional State(s)": "Nutkání se ublížit; Hněv/vztek; Ruminace",
        "Activation Energy": "Střední",
        "Time to Effect": "Krátký až střední (5–10 min)",
        "Duration of Activity": "10–20 min",
        "Required Objects": "Nic",
        "Setting Constraints": "Spíše klid",
        "Brief Mechanism": "Všímavé sledování nutkání jako vlny → přijetí místo potlačení; intenzita vrcholí a klesá; nižší reaktivita bez souzení.",
        "Bridges to Help-Seeking": "Ne",
        "Repeatability": "Opakovatelné (dovednost roste tréninkem)",
        "Evidence Strength": "Silná",
        "Czech Adaptation Notes": "Linka bezpečí #zvladni20: špičky nutkání často do ~20 minut.",
    },
    "K07": {
        "ID": "K07",
        "Name (Professional)": "Kognitivní odvedení pozornosti (Počítání)",
        "Name (Child-friendly)": "Těžké počty",
        "Modality": "Kognitivní",
        "Source(s)": "DBT rozptýlení (ACCEPTS — Aktivity); konsensus; zvládání disociace",
        "Age Range": "8–18",
        "Target Emotional State(s)": "Akutní panika; Disociace/pocit ne reality; Ruminace",
        "Activation Energy": "Nízká",
        "Time to Effect": "Okamžitý (15–30 s)",
        "Duration of Activity": "1–5 min",
        "Required Objects": "Nic",
        "Setting Constraints": "Kdekoli (zcela nenápadné)",
        "Brief Mechanism": "Počítání pozpátku po sedmičkách (u mladších jednodušší) zatěžuje PF kůru → konkuruje emočnímu zpracování; vrací do přítomnosti.",
        "Bridges to Help-Seeking": "Ne",
        "Repeatability": "Lze opakovat neomezeně",
        "Evidence Strength": "Střední",
        "Czech Adaptation Notes": "Nepanikař obsahuje modul „Počítání“.",
    },
    "K08": {
        "ID": "K08",
        "Name (Professional)": "Analýza důsledků (Pro a proti)",
        "Name (Child-friendly)": "Pro a proti",
        "Modality": "Kognitivní",
        "Source(s)": "DBT Pro a proti (Linehan, 2015); adolescentní KBT",
        "Age Range": "13–18",
        "Target Emotional State(s)": "Nutkání se ublížit; Hněv/vztek (před impulzivním činem)",
        "Activation Energy": "Střední",
        "Time to Effect": "Krátký až střední (5–10 min)",
        "Duration of Activity": "5–15 min",
        "Required Objects": "Papír + pero (nebo jen v hlavě)",
        "Setting Constraints": "Spíše soukromí",
        "Brief Mechanism": "Strukturované zhodnocení krátkodobých vs dlouhodobých důsledků zapojuje racionální část; připraví závazek použít dovednosti; lze mít předem kartičku.",
        "Bridges to Help-Seeking": "Ne",
        "Repeatability": "Opakovatelné (přehled předepsaného seznamu)",
        "Evidence Strength": "Silná",
        "Czech Adaptation Notes": None,
    },
    "SA01": {
        "ID": "SA01",
        "Name (Professional)": "Projektivní dialog (Přechodový objekt)",
        "Name (Child-friendly)": "Pokec s plyšákem",
        "Modality": "Blízké sociální",
        "Source(s)": "Teorie přechodného objektu (Winnicott); narativní terapie; doporučení pro mladší děti",
        "Age Range": "8–14 (někdy i teen)",
        "Target Emotional State(s)": "Osamělost; Smutek/ochromení; Stud; Difúzní úzkost",
        "Activation Energy": "Nízká až střední",
        "Time to Effect": "Krátký (2–5 min)",
        "Duration of Activity": "5–20 min",
        "Required Objects": "Plyšák, polštář, mazlíček (je-li), jakýkoli předmět",
        "Setting Constraints": "Soukromý prostor",
        "Brief Mechanism": "Externalizace dialogem s předmětem; trénink hlasitého pojmenování pocitů; přechodný objekt dává pocit spojení a bezpečí.",
        "Bridges to Help-Seeking": "Ano (zkouší verbalizaci → snazší říct člověku)",
        "Repeatability": "Opakovatelné",
        "Evidence Strength": "Střední",
        "Czech Adaptation Notes": "Most k volání Linky bezpečí 116 111.",
    },
    "SA02": {
        "ID": "SA02",
        "Name (Professional)": "Behaviorální nácvik rozhovoru",
        "Name (Child-friendly)": "Zkouška nanečisto",
        "Modality": "Blízké sociální",
        "Source(s)": "Behaviorální nácvik v KBT; sociální dovednosti; konsensus",
        "Age Range": "10–18",
        "Target Emotional State(s)": "Stud; Stres ve škole; Osamělost; Difúzní úzkost",
        "Activation Energy": "Střední",
        "Time to Effect": "Střední (5–10 min)",
        "Duration of Activity": "5–20 min",
        "Required Objects": "Nic (volitelně zrcadlo)",
        "Setting Constraints": "Soukromý prostor",
        "Brief Mechanism": "Nácvik snižuje anticipační úzkost před skutečným prozrazením; buduje sebeúčinnost pro vyhledání pomoci; desenzibilizace opakováním.",
        "Bridges to Help-Seeking": "Ano (přímo trénuje vyhledání pomoci)",
        "Repeatability": "Opakovatelné",
        "Evidence Strength": "Střední",
        "Czech Adaptation Notes": "Doporučeno jako most k volání Linky bezpečí nebo školnímu psychologovi.",
    },
    "SA03": {
        "ID": "SA03",
        "Name (Professional)": "Časový kognitivní odstup",
        "Name (Child-friendly)": "Dopis do budoucna",
        "Modality": "Blízké sociální",
        "Source(s)": "Narativní terapie; pozitivní psychologie; sebesoucit",
        "Age Range": "10–18",
        "Target Emotional State(s)": "Smutek/ochromení; Osamělost; Ruminace; Stud",
        "Activation Energy": "Střední",
        "Time to Effect": "Střední (10–15 min)",
        "Duration of Activity": "10–20 min",
        "Required Objects": "Papír + pero (nebo e-mail/poznámky)",
        "Setting Constraints": "Soukromý prostor",
        "Brief Mechanism": "Časový odstup (psaní budoucímu já) dává naději a perspektivu; rámec sebesoucitu; lze znovu číst v další tísni.",
        "Bridges to Help-Seeking": "Ne",
        "Repeatability": "Střední (jeden dopis na epizodu; měnit výzvy)",
        "Evidence Strength": "Střední",
        "Czech Adaptation Notes": None,
    },
    "SA04": {
        "ID": "SA04",
        "Name (Professional)": "Trénink pozitivního vybavování (Vděčnost)",
        "Name (Child-friendly)": "Tři radosti",
        "Modality": "Blízké sociální",
        "Source(s)": "Seligman et al. (2005) RCT; Emmons & McCullough (2003); Nepanikař „Co mě potěšilo“",
        "Age Range": "8–18",
        "Target Emotional State(s)": "Smutek/ochromení; Ruminace; Osamělost; Potíže se spánkem",
        "Activation Energy": "Nízká až střední",
        "Time to Effect": "Krátký (2–5 min)",
        "Duration of Activity": "3–10 min",
        "Required Objects": "Papír + pero (nebo v hlavě / telefon)",
        "Setting Constraints": "Kdekoli",
        "Brief Mechanism": "Posouvá pozornost od hrozby k pozitivu; vychutnání aktivuje odměny; trénuje vybavování dobrého; proti negativity bias.",
        "Bridges to Help-Seeking": "Ne",
        "Repeatability": "Denně opakovatelné",
        "Evidence Strength": "Silná",
        "Czech Adaptation Notes": "Nepanikař obsahuje modul „Co mě potěšilo“.",
    },
    "SA05": {
        "ID": "SA05",
        "Name (Professional)": "Aktivace vnitřního podpůrného systému",
        "Name (Child-friendly)": "Vnitřní kouč",
        "Modality": "Blízké sociální",
        "Source(s)": "Sebesoucit (Neff, 2003); CFT (Gilbert, 2009); Nevypusť duši",
        "Age Range": "10–18 (8–10 zjednodušit)",
        "Target Emotional State(s)": "Stud; Smutek/ochromení; Osamělost; Nutkání se ublížit; Ruminace",
        "Activation Energy": "Nízká až střední",
        "Time to Effect": "Okamžitý až krátký (1–3 min)",
        "Duration of Activity": "2–10 min",
        "Required Objects": "Nic",
        "Setting Constraints": "Kdekoli (uvnitř nebo šeptem)",
        "Brief Mechanism": "Aktivuje affiliativní/uklidňující systém → méně sebekritiky založené na hrozbě; nižší kortizol; opakováním posiluje dráhy sebesoucitu.",
        "Bridges to Help-Seeking": "Ano (trénuje soucitný jazyk)",
        "Repeatability": "Lze opakovat neomezeně",
        "Evidence Strength": "Silná",
        "Czech Adaptation Notes": "Nevypusť duši: „Mrzí mě, že se takhle cítíš, a mám tě rád.“",
    },
    "SA06": {
        "ID": "SA06",
        "Name (Professional)": "Asistovaná regulace afektu (Linka pomoci)",
        "Name (Child-friendly)": "Napsat o pomoc",
        "Modality": "Blízké sociální",
        "Source(s)": "Chat Linky bezpečí; výzkum krizových textových linek; WHO o službách pro mládež",
        "Age Range": "8–18",
        "Target Emotional State(s)": "Jakýkoli stav; Nutkání se ublížit; Osamělost; Akutní panika",
        "Activation Energy": "Střední až vysoká",
        "Time to Effect": "Krátký až střední (odpověď se liší)",
        "Duration of Activity": "10–60 min",
        "Required Objects": "Telefon s internetem",
        "Setting Constraints": "Soukromí pro psaní",
        "Brief Mechanism": "Text snižuje práh oproti hovoru; anonymita může snížit stud; odborné vedení v reálném čase; plný most k pomoci.",
        "Bridges to Help-Seeking": "Ano (je to vyhledání pomoci)",
        "Repeatability": "Podle potřeby",
        "Evidence Strength": "Silná",
        "Czech Adaptation Notes": "Chat Linky bezpečí: chat.linkabezpeci.cz; e-mail pomoc@linkabezpeci.cz; zdarma, anonymně, pro děti/mládež do 26 let.",
    },
    "N01": {
        "ID": "N01",
        "Name (Professional)": "Somatické uzemnění v přírodě (Earthing)",
        "Name (Child-friendly)": "Bosé nohy",
        "Modality": "Příroda",
        "Source(s)": "Výzkum earthing/grounding (Chevalier et al., 2012); somatické uzemnění",
        "Age Range": "8–18",
        "Target Emotional State(s)": "Disociace/pocit ne reality; Difúzní úzkost; Ruminace; Hněv/vztek",
        "Activation Energy": "Nízká",
        "Time to Effect": "Okamžitý až krátký (1–5 min)",
        "Duration of Activity": "5–15 min",
        "Required Objects": "Bezpečný povrch (tráva, hlína, písek)",
        "Setting Constraints": "Venku na bezpečném povrchu",
        "Brief Mechanism": "Přímý kontakt chodidel se zemí; silné smyslové ukotvení; částečně diskutovaný efekt na kortizol; hlavně smyslová reorientace.",
        "Bridges to Help-Seeking": "Ne",
        "Repeatability": "Opakovatelné",
        "Evidence Strength": "Vznikající",
        "Czech Adaptation Notes": "Dostupné v parcích, zahradách, venkově.",
    },
    "N02": {
        "ID": "N02",
        "Name (Professional)": "Aktivní obnova pozornosti v přírodě",
        "Name (Child-friendly)": "Lov pokladů",
        "Modality": "Příroda",
        "Source(s)": "Teorie obnovy pozornosti (Kaplan, 1995); terapie v přírodě; úprava 5-4-3-2-1 venku",
        "Age Range": "8–14 (upravit pro teen)",
        "Target Emotional State(s)": "Difúzní úzkost; Ruminace; Smutek/ochromení; Stres ve škole",
        "Activation Energy": "Střední",
        "Time to Effect": "Krátký až střední (5–10 min)",
        "Duration of Activity": "10–30 min",
        "Required Objects": "Nic (volitelně telefon na fotky)",
        "Setting Constraints": "Venku",
        "Brief Mechanism": "Spojuje smyslové ukotvení s jemnou fascinací přírody; obnova pozornosti → odpočinek řízené pozornosti.",
        "Bridges to Help-Seeking": "Ne",
        "Repeatability": "Opakovatelné (pokaždé jiné nálezy)",
        "Evidence Strength": "Střední",
        "Czech Adaptation Notes": "České lesy, parky a řeky nabízejí bohaté podněty.",
    },
    "N03": {
        "ID": "N03",
        "Name (Professional)": "Zraková fascinace a všímavost",
        "Name (Child-friendly)": "Pozorování mraků",
        "Modality": "Příroda",
        "Source(s)": "Všímavost; teorie obnovy pozornosti; doporučení kliniků",
        "Age Range": "8–18",
        "Target Emotional State(s)": "Ruminace; Difúzní úzkost; Smutek/ochromení; Osamělost",
        "Activation Energy": "Nízká",
        "Time to Effect": "Krátký (2–5 min)",
        "Duration of Activity": "5–30 min",
        "Required Objects": "Nic",
        "Setting Constraints": "Venku nebo u okna",
        "Brief Mechanism": "Široké zorné pole snižuje „tunel“ hrozy; obloha dává prostor bez souzení; jemná fascinace.",
        "Bridges to Help-Seeking": "Ne",
        "Repeatability": "Lze opakovat neomezeně",
        "Evidence Strength": "Vznikající",
        "Czech Adaptation Notes": None,
    },
    "H01": {
        "ID": "H01",
        "Name (Professional)": "Kognitivní defúze humorem",
        "Name (Child-friendly)": "Legrační hlas",
        "Modality": "Humor",
        "Source(s)": "ACT defúze (Hayes); humor v terapii; doporučení kliniků",
        "Age Range": "8–18",
        "Target Emotional State(s)": "Ruminace; Stud; Stres ve škole; Difúzní úzkost",
        "Activation Energy": "Nízká až střední",
        "Time to Effect": "Okamžitý (15–60 s)",
        "Duration of Activity": "1–5 min",
        "Required Objects": "Nic",
        "Setting Constraints": "Soukromí (nebo šeptem)",
        "Brief Mechanism": "Opakování úzkostné myšlenky kresleným hlasem/přízvukem → defúze; snižuje věrohodnost a náboj; humor aktivuje odměny.",
        "Bridges to Help-Seeking": "Ne",
        "Repeatability": "Lze opakovat neomezeně",
        "Evidence Strength": "Střední",
        "Czech Adaptation Notes": None,
    },
    "H02": {
        "ID": "H02",
        "Name (Professional)": "Indukce pozitivního afektu (Video)",
        "Name (Child-friendly)": "Vtipné video",
        "Modality": "Humor",
        "Source(s)": "Pozitivní psychologie; humor jako zvládání (Martin, 2007); rozptýlení v DBT ACCEPTS",
        "Age Range": "10–18",
        "Target Emotional State(s)": "Smutek/ochromení; Osamělost; Difúzní úzkost; Ruminace",
        "Activation Energy": "Nízká",
        "Time to Effect": "Okamžitý až krátký (1–3 min)",
        "Duration of Activity": "5–15 min",
        "Required Objects": "Telefon/zařízení",
        "Setting Constraints": "Kdekoli s telefonem",
        "Brief Mechanism": "Smích spouští endorfiny; změna mimických svalů → signál mozku pro pozitivní afekt; kognitivní rozptýlení.",
        "Bridges to Help-Seeking": "Ne",
        "Repeatability": "Opakovatelné (různý obsah)",
        "Evidence Strength": "Střední",
        "Czech Adaptation Notes": None,
    },
    "R01": {
        "ID": "R01",
        "Name (Professional)": "Příprava krizových pomůcek",
        "Name (Child-friendly)": "Krabička záchrany",
        "Modality": "Rituál",
        "Source(s)": "Protokoly bezpečnostního plánu; DBT sada pro přežití krize; doporučení kliniků",
        "Age Range": "8–18",
        "Target Emotional State(s)": "Preventivně/všechny stavy (připraveno před krizí)",
        "Activation Energy": "Vysoká (zpočátku); Nízká (po sestavení)",
        "Time to Effect": "N/A (přípravná aktivita)",
        "Duration of Activity": "30–60 min sestavení; 1–5 min použití",
        "Required Objects": "Krabice/taška + vybrané předměty (viz seznam)",
        "Setting Constraints": "Doma (stavba); Kdekoli (použití)",
        "Brief Mechanism": "Samotná příprava buduje sebeúčinnost; předvýběr snižuje rozhodovací únavu v krizi; hmatatelné připomíná, že zvládnutí je možné.",
        "Bridges to Help-Seeking": "Ano (čísla linek v krabičce)",
        "Repeatability": "Znovupoužitelné; občas aktualizovat",
        "Evidence Strength": "Střední",
        "Czech Adaptation Notes": "Lze vložit kartičku Linky bezpečí (116 111), připomínku Nepanikař, vůni, fidget, psaná ujištění.",
    },
    "R02": {
        "ID": "R02",
        "Name (Professional)": "Cirkadiánní spánkový rituál",
        "Name (Child-friendly)": "Večerní klid",
        "Modality": "Rituál",
        "Source(s)": "Spánková hygiena; CBT-I pro teen; konsensus",
        "Age Range": "8–18",
        "Target Emotional State(s)": "Potíže se spánkem; Difúzní úzkost; Ruminace",
        "Activation Energy": "Střední",
        "Time to Effect": "Střední (10–20 min)",
        "Duration of Activity": "15–30 min",
        "Required Objects": "Nic (volitelně deník, vůně, hudba)",
        "Setting Constraints": "Domov/ložnice",
        "Brief Mechanism": "Stálý rituál před spaním signalizuje cirkadiánní systém; předvídatelnost snižuje úzkost před usínáním; kombinuje nízkoaktivační techniky.",
        "Bridges to Help-Seeking": "Ne",
        "Repeatability": "Denně (buduje zvyk)",
        "Evidence Strength": "Silná",
        "Czech Adaptation Notes": None,
    },
    "R03": {
        "ID": "R03",
        "Name (Professional)": "Ranní interoceptivní zhodnocení",
        "Name (Child-friendly)": "Ranní start",
        "Modality": "Rituál",
        "Source(s)": "Všímavost; pozitivní psychologie; doporučení kliniků",
        "Age Range": "10–18",
        "Target Emotional State(s)": "Difúzní úzkost; Ruminace; Smutek/ochromení; Stres ve škole",
        "Activation Energy": "Nízká",
        "Time to Effect": "Krátký (2–3 min)",
        "Duration of Activity": "2–5 min",
        "Required Objects": "Nic (volitelně deník)",
        "Setting Constraints": "Kdekoli (doma, škola)",
        "Brief Mechanism": "Tři otázky: Jak se cítím? Co potřebuji? Co dnes udělám jedno pro sebe? — buduje interocepci a agenturu; denně posiluje emoční slovník.",
        "Bridges to Help-Seeking": "Ano (vzorce → snazší sdělit někomu)",
        "Repeatability": "Denně opakovatelné",
        "Evidence Strength": "Střední",
        "Czech Adaptation Notes": None,
    },

    "B13": {
        "ID": "B13",
        "Name (Professional)": "Aktivace lícního nervu (Poloviční úsměv)",
        "Name (Child-friendly)": "Lehký úsměv",
        "Modality": "Tělo",
        "Source(s)": "32",
        "Age Range": "8–18",
        "Target Emotional State(s)": "Anger/rage, rigid defiance, urge to self-harm",
        "Activation Energy": "Nízká",
        "Time to Effect": "Krátký (1–5 min)",
        "Duration of Activity": "1–5 minutes",
        "Required Objects": "Nic",
        "Setting Constraints": "Kdekoli",
        "Brief Mechanism": "Utilizes the facial feedback hypothesis; relaxing facial muscles and opening hands biologically contradicts the physiology of anger.",
        "Bridges to Help-Seeking": "Ne",
        "Repeatability": "Lze opakovat neomezeně",
        "Evidence Strength": "Silná (DBT)",
        "Czech Adaptation Notes": "",
    },
    "S09": {
        "ID": "S09",
        "Name (Professional)": "Záměrná sluchová diskriminace",
        "Name (Child-friendly)": "Bystré ucho",
        "Modality": "Smysly",
        "Source(s)": "8",
        "Age Range": "8–18",
        "Target Emotional State(s)": "Diffuse anxiety, thought spirals",
        "Activation Energy": "Nízká",
        "Time to Effect": "Krátký (1–5 min)",
        "Duration of Activity": "3 minutes",
        "Required Objects": "Nic",
        "Setting Constraints": "Kdekoli",
        "Brief Mechanism": "Shifting auditory focus from loud to quiet noises requires sustained attentional control, which disrupts catastrophic thought spirals.",
        "Bridges to Help-Seeking": "Ne",
        "Repeatability": "Vysoká",
        "Evidence Strength": "Silná (DBT)",
        "Czech Adaptation Notes": "",
    },
    "S10": {
        "ID": "S10",
        "Name (Professional)": "Termální regulace afektu",
        "Name (Child-friendly)": "Hřejivý hrnek",
        "Modality": "Smysly",
        "Source(s)": "36",
        "Age Range": "8–18",
        "Target Emotional State(s)": "Sadness, numbness, loneliness",
        "Activation Energy": "Střední",
        "Time to Effect": "Střední (5–20 min)",
        "Duration of Activity": "10–15 minutes",
        "Required Objects": "Hot beverage, mug",
        "Setting Constraints": "Home / Kitchen access",
        "Brief Mechanism": "Radiant warmth on hands and sweet liquids mimic evolutionary markers of safety and maternal buffering, triggering dopamine.",
        "Bridges to Help-Seeking": "Ne",
        "Repeatability": "Nízká",
        "Evidence Strength": "Tradiční",
        "Czech Adaptation Notes": "",
    },
    "S11": {
        "ID": "S11",
        "Name (Professional)": "Vizuální okulomotorické sledování",
        "Name (Child-friendly)": "Obkreslování okem",
        "Modality": "Smysly",
        "Source(s)": "35",
        "Age Range": "8–18",
        "Target Emotional State(s)": "School-related stress, acute panic",
        "Activation Energy": "Nízká",
        "Time to Effect": "Krátký (1–5 min)",
        "Duration of Activity": "2 minutes",
        "Required Objects": "Nic",
        "Setting Constraints": "Kdekoli",
        "Brief Mechanism": "Tracing the physical outline of a hand forces eyes into deliberate, slow paths, synchronizing breath with visual tracking.",
        "Bridges to Help-Seeking": "Ne",
        "Repeatability": "Vysoká",
        "Evidence Strength": "Střední",
        "Czech Adaptation Notes": "",
    },
    "C11": {
        "ID": "C11",
        "Name (Professional)": "Kinetický výboj čmáráním",
        "Name (Child-friendly)": "Čmárání pocitů",
        "Modality": "Tvořivé",
        "Source(s)": "21",
        "Age Range": "8–18",
        "Target Emotional State(s)": "Anger/rage, urge to self-harm, frustration",
        "Activation Energy": "Nízká",
        "Time to Effect": "Okamžitý (sec–1 min)",
        "Duration of Activity": "2–5 minutes",
        "Required Objects": "Paper, crayons/pens",
        "Setting Constraints": "Kdekoli",
        "Brief Mechanism": "Rapid, aggressive motor movements on paper safely discharge kinetic energy associated with the fight response without bodily harm.",
        "Bridges to Help-Seeking": "Ne",
        "Repeatability": "Vysoká",
        "Evidence Strength": "Střední",
        "Czech Adaptation Notes": "",
    },
    "C12": {
        "ID": "C12",
        "Name (Professional)": "Jemnomotorická fokusace (Origami)",
        "Name (Child-friendly)": "Skládání papíru",
        "Modality": "Tvořivé",
        "Source(s)": "39",
        "Age Range": "8–18",
        "Target Emotional State(s)": "Rumination, diffuse anxiety, school stress",
        "Activation Energy": "Střední",
        "Time to Effect": "Střední (5–20 min)",
        "Duration of Activity": "10–20 minutes",
        "Required Objects": "Paper",
        "Setting Constraints": "Flat surface",
        "Brief Mechanism": "Precise, repetitive fine-motor movements demand concentration, drawing cognitive resources away from anxiety while providing mastery.",
        "Bridges to Help-Seeking": "Ne",
        "Repeatability": "Vysoká",
        "Evidence Strength": "Vznikající",
        "Czech Adaptation Notes": "",
    },
    "C13": {
        "ID": "C13",
        "Name (Professional)": "Bilaterální rytmická stimulace",
        "Name (Child-friendly)": "Vytloukání rytmu",
        "Modality": "Tvořivé",
        "Source(s)": "21",
        "Age Range": "8–18",
        "Target Emotional State(s)": "Anger/rage, dissociation",
        "Activation Energy": "Nízká",
        "Time to Effect": "Krátký (1–5 min)",
        "Duration of Activity": "3–5 minutes",
        "Required Objects": "Nic (hands on thighs)",
        "Setting Constraints": "Tolerant of mild noise",
        "Brief Mechanism": "Rhythmic, bilateral tapping bypasses higher cognitive functioning to establish a predictable physical tempo that counteracts internal chaos.",
        "Bridges to Help-Seeking": "Ne",
        "Repeatability": "Vysoká",
        "Evidence Strength": "Střední",
        "Czech Adaptation Notes": "",
    },
    "K09": {
        "ID": "K09",
        "Name (Professional)": "Radikální přijetí reality (DBT)",
        "Name (Child-friendly)": "Zkrátka to tak je",
        "Modality": "Kognitivní",
        "Source(s)": "19",
        "Age Range": "13–18",
        "Target Emotional State(s)": "Anger, sadness, frustration over unchangeable events",
        "Activation Energy": "Vysoká",
        "Time to Effect": "Střední (5–20 min)",
        "Duration of Activity": "1–2 minutes",
        "Required Objects": "Nic",
        "Setting Constraints": "Kdekoli",
        "Brief Mechanism": "Ceasing to fight reality halts the secondary suffering caused by psychological resistance, reducing escalation of the emotional response.",
        "Bridges to Help-Seeking": "Ne",
        "Repeatability": "Vysoká",
        "Evidence Strength": "Silná (DBT)",
        "Czech Adaptation Notes": "",
    },
    "N04": {
        "ID": "N04",
        "Name (Professional)": "Vizuální zpracování přírodních fraktálů",
        "Name (Child-friendly)": "Vzory v přírodě",
        "Modality": "Příroda",
        "Source(s)": "47",
        "Age Range": "8–18",
        "Target Emotional State(s)": "Overwhelm, sensory overload indoors",
        "Activation Energy": "Nízká",
        "Time to Effect": "Krátký (1–5 min)",
        "Duration of Activity": "5 minutes",
        "Required Objects": "Leaf, tree bark",
        "Setting Constraints": "Outdoors or houseplant",
        "Brief Mechanism": "The human visual system is optimized for natural fractals; processing these patterns significantly reduces physiological stress and strain.",
        "Bridges to Help-Seeking": "Ne",
        "Repeatability": "Vysoká",
        "Evidence Strength": "Vznikající",
        "Czech Adaptation Notes": "",
    },
    "N05": {
        "ID": "N05",
        "Name (Professional)": "Terapeutický pobyt v přírodě",
        "Name (Child-friendly)": "Moje místo venku",
        "Modality": "Příroda",
        "Source(s)": "48",
        "Age Range": "13–18",
        "Target Emotional State(s)": "Chronic stress, school anxiety, sadness",
        "Activation Energy": "Střední",
        "Time to Effect": "Prodloužený (20+ min)",
        "Duration of Activity": "20+ minutes",
        "Required Objects": "Nic",
        "Setting Constraints": "Safe outdoor space",
        "Brief Mechanism": "Sustained immersion in a natural environment significantly lowers cortisol levels, facilitating deep emotional processing away from pressures.",
        "Bridges to Help-Seeking": "Ne",
        "Repeatability": "Vysoká",
        "Evidence Strength": "Silná",
        "Czech Adaptation Notes": "",
    },
    "H03": {
        "ID": "H03",
        "Name (Professional)": "Okamžité přepnutí afektu",
        "Name (Child-friendly)": "Krabice smíchu",
        "Modality": "Humor",
        "Source(s)": "10",
        "Age Range": "8–18",
        "Target Emotional State(s)": "Diffuse anxiety, sadness, rumination",
        "Activation Energy": "Nízká",
        "Time to Effect": "Okamžitý (sec–1 min)",
        "Duration of Activity": "5–15 minutes",
        "Required Objects": "Smartphone / memes",
        "Setting Constraints": "Kdekoli",
        "Brief Mechanism": "Rapidly introduces positive affective stimuli, triggering dopamine release and short-circuiting neural pathways processing sadness.",
        "Bridges to Help-Seeking": "Ne",
        "Repeatability": "Vysoká",
        "Evidence Strength": "Silná",
        "Czech Adaptation Notes": "",
    },
    "H04": {
        "ID": "H04",
        "Name (Professional)": "Absurdní kognitivní přerámování",
        "Name (Child-friendly)": "Směšný filtr",
        "Modality": "Humor",
        "Source(s)": "52",
        "Age Range": "13–18",
        "Target Emotional State(s)": "Shame, social anxiety, fear of failure",
        "Activation Energy": "Střední",
        "Time to Effect": "Krátký (1–5 min)",
        "Duration of Activity": "2 minutes",
        "Required Objects": "Nic",
        "Setting Constraints": "Kdekoli",
        "Brief Mechanism": "Mentally visualizing a feared scenario with an absurd filter structurally defuses the threat response associated with the memory.",
        "Bridges to Help-Seeking": "Ne",
        "Repeatability": "Střední",
        "Evidence Strength": "Střední",
        "Czech Adaptation Notes": "",
    },
    "H05": {
        "ID": "H05",
        "Name (Professional)": "Paradoxní intence (Přehánění)",
        "Name (Child-friendly)": "Přitažené za vlasy",
        "Modality": "Humor",
        "Source(s)": "10",
        "Age Range": "13–18",
        "Target Emotional State(s)": "Catastrophizing, thought spirals",
        "Activation Energy": "Střední",
        "Time to Effect": "Krátký (1–5 min)",
        "Duration of Activity": "2–5 minutes",
        "Required Objects": "Nic",
        "Setting Constraints": "Kdekoli",
        "Brief Mechanism": "Intentionally exaggerating an anxious thought until it becomes logically impossible exposes irrationality, inducing relief through paradox.",
        "Bridges to Help-Seeking": "Ne",
        "Repeatability": "Střední",
        "Evidence Strength": "Vznikající",
        "Czech Adaptation Notes": "",
    },
    "H06": {
        "ID": "H06",
        "Name (Professional)": "Respirační modifikace smíchem",
        "Name (Child-friendly)": "Smějící se dech",
        "Modality": "Humor",
        "Source(s)": "53",
        "Age Range": "8–12",
        "Target Emotional State(s)": "Physical tension, sadness",
        "Activation Energy": "Vysoká",
        "Time to Effect": "Krátký (1–5 min)",
        "Duration of Activity": "3–5 minutes",
        "Required Objects": "Nic",
        "Setting Constraints": "Private space",
        "Brief Mechanism": "Forced laughter alters respiratory patterns, extending exhalations to expel tension, eventually triggering genuine endorphin release.",
        "Bridges to Help-Seeking": "Ne",
        "Repeatability": "Vysoká",
        "Evidence Strength": "Střední",
        "Czech Adaptation Notes": "",
    },
    "R04": {
        "ID": "R04",
        "Name (Professional)": "Přechodový rituál proti úzkosti",
        "Name (Child-friendly)": "Tři kroky",
        "Modality": "Rituál",
        "Source(s)": "11",
        "Age Range": "8–18",
        "Target Emotional State(s)": "School stress, environmental transitions",
        "Activation Energy": "Nízká",
        "Time to Effect": "Krátký (1–5 min)",
        "Duration of Activity": "2 minutes",
        "Required Objects": "Nic",
        "Setting Constraints": "Kdekoli",
        "Brief Mechanism": "A strict three-step sequence (e.g., wash hands, breathe, touch object) signals the brain that a stressful phase has ended and safety has begun.",
        "Bridges to Help-Seeking": "Ne",
        "Repeatability": "Vysoká",
        "Evidence Strength": "Silná",
        "Czech Adaptation Notes": "",
    },
}
